project:
  type: website

website:
  title: "Engine Displacement"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: sources.qmd
        text: Sources
      - href: source-1.qmd
        text: Data
        
        
  sidebar: 
    -id: sources
    title: "Sources"
    style: "floating"
    background: "#ffffff"
    collapse-level: 2
    contents:
      - source-1.qmd
      - source-2.qmd
    


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


## Mutate for conversion units


