---
title: "new-final-project"
---
```{r}
#| echo: false

library(tidyverse)
library(primer.data)
library(rstanarm)

cars <- read_csv(file = "Automobile.csv", show_col_types = FALSE)
cars_graph <- cars |> ggplot(aes(x = displacement, y = mpg)) + geom_point() + labs(title = "The Effect of Engine Displacement on Gas Mileage", x = "Engine Displacement", y = "Miles Per Gallon", subtitle = "Generally, as engine displacement increases, gas mileage decreases", caption = "Kaggle: Car Information Dataset") + theme_classic()



fit_obj <- stan_glm(data = cars, 
                    formula = mpg ~ cylinders + displacement, 
                    family = gaussian, 
                    refresh = 0,
                    seed = 9)

cars_graph

```
## Analysis
This is from a common dataset on cars. I chose to compare the engine displacement on gas mileage. Engine displacement is the amount of air the engine can combust. A 5.7L can hold and ignite that much air in the cylinders combined. Not suprisingly, higher displacement engines have a worse fuel economy because they burn more fuel.
```{r}
fit_obj <- stan_glm(data = cars, 
                    formula = mpg ~ cylinders + displacement, 
                    family = gaussian, 
                    refresh = 0,
                    seed = 9)

fit_obj


```

